In [1]:
import networkExpansionPy.folds as nf
import pandas as pd
from collections import Counter
from pathlib import PurePath, Path

# seed = sys.argv[1]
# random.seed(seed)
asset_path = nf.asset_path

# for vanilla
METABOLISM_PATH = PurePath(asset_path, "metabolic_networks","metabolism.v8.01May2023.pkl") # path to metabolism object pickle
RN2RULES_PATH = PurePath(asset_path,"rn2fold","rn2rules.20230224.pkl") # path to rn2rules object pickle
SEED_CPDS_PATH = PurePath(asset_path, "compounds", "seeds.Goldford2022.csv") # path to seed compounds csv

# for FOLD-GATED
ALGORITHM = "no_look_ahead_rules"
WRITE = True # write result to disk
WRITE_TMP = False # write after each iteration
CUSTOM_WRITE_PATH = None # if writing result, custom path to write to
STR_TO_APPEND_TO_FNAME = None # if writing result, str to append to filename
ORDERED_OUTCOME = False # ignore random seed and always choose folds based on sort order
IGNORE_REACTION_VERSIONS = True # when maximizing for reactions, don't count versioned reactions

## Metabolism
metabolism = pd.read_pickle(METABOLISM_PATH)
# # remove reactions that produce H2O2 before O2
# H2O2_rns = ['R00017_v1', 'R03532_v1', 'R09507_v1', 'R09740_v1', 'R09741_v1', 'R11522', 'R12455', 'R12454']
# condition = ((metabolism.network['rn'].isin(H2O2_rns)) & (metabolism.network['direction'] == 'reverse'))
# metabolism.network = metabolism.network[~condition]
# assert 'R00017_v1' not in list(metabolism.network['rn'])

## Ablation
# metabolism.pruneReactionsFromMetabolite(['C00024'])
# metabolism.pruneReactionsFromMetabolite(['C01847'])
# metabolism.pruneReactionsFromMetabolite(['Z00009'])
# metabolism.pruneReactionsFromMetabolite(['C03283'])
# metabolism.pruneReactionsFromMetabolite(['C00986'])


## FoldRules
rn2rules = pd.read_pickle(RN2RULES_PATH)
foldrules = nf.FoldRules.from_rn2rules(rn2rules)

## Modify seeds with AA and GATP_rns
aa_cids = set(["C00037",
    "C00041",
    "C00065",
    "C00188",
    "C00183",
    "C00407",
    "C00123",
    "C00148",
    "C00049",
    "C00025"])

GATP_rns = {'R00200_gATP_v1',
    'R00200_gATP_v2',
    'R00430_gGTP_v1',
    'R00430_gGTP_v2',
    'R01523_gATP_v1',
    'R04144_gATP_v1',
    'R04208_gATP',
    'R04463_gATP',
    'R04591_gATP_v1',
    'R06836_gATP',
    'R06974_gATP',
    'R06975_gATP_v1'}


## Seed
seed = nf.Params(
    rns = set(metabolism.network["rn"]) - set(rn2rules) | GATP_rns,  # start with non-fold-gated reactions + GATP_rns
    cpds = set((pd.read_csv(SEED_CPDS_PATH)["ID"])) | aa_cids,
    folds = set(['spontaneous'])
)

## Seed with pre-expansion
# preALL = pd.read_pickle('../data/pre-expansion_seed_cpds/pre-expansion_seed_cpds_ALL.pkl')
# seed = nf.Params(
#     rns = set(metabolism.network["rn"]) - set(rn2rules) | GATP_rns,  # start with non-fold-gated reactions + GATP_rns
#     cpds = set(preALL) | aa_cids,
#     folds = set(['spontaneous'])
# )

# ## Inititalize fold metabolism
fm = nf.FoldMetabolism(metabolism, foldrules, seed)

# ## run FOLD-GATED expansion
# result = fm.rule_order(algorithm=ALGORITHM, write=WRITE, write_tmp=WRITE_TMP, path=CUSTOM_WRITE_PATH, str_to_append_to_fname=STR_TO_APPEND_TO_FNAME, ordered_outcome=ORDERED_OUTCOME, ignore_reaction_versions=IGNORE_REACTION_VERSIONS)

calculating scope...

/Users/tseamuscorlett/Desktop/LongoLab/Fold_Gated/networkExpansion/networkExpansionPy/lib.py:556: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  X,Y = netExp_trace(R,P,x0,b)

...done.

In [2]:
len(metabolism.network['rn'])

105986

In [20]:
directO2 = {'R09513_v1', 'R07997_v1', 'R11573', 'R02383_v1', 'R06468', 'R10790_v1', 'R10162_v1', 'R11817', 'R11713_v3', 'R06633_v1', 'R12167_v1', 'R11620_v1', 'R11984_v1', 'R04890_v1', 'R06759', 'R12663', 'R10882', 'R04904_v1', 'R07958_v1', 'R08852', 'R07055', 'R02894_v1', 'R04376_v1', 'R02532_v1', 'R11053_v1', 'R12007', 'R05320_v1', 'R03369_v1', 'R01814_v1', 'R00677_v2', 'R12452_v1', 'R07224_v1', 'R03204', 'R04280_v1', 'R07978_v2', 'R00033_v1', 'R04066_v1', 'R07525_v1', 'R00800', 'R10160_v1', 'R06624', 'R10576_v1', 'R11742_v1', 'R10143_v1', 'R09813_v1', 'R02657_v2', 'R10722_v1', 'R10031_v1', 'R06947_v1', 'R05280', 'R05466_v1', 'R02173_v3', 'R05299_v1', 'R11712_v1', 'R08685', 'R01372_v1', 'R01184_v1', 'R12418', 'R08795_v1', 'R03092', 'R09517', 'R01203', 'R05698', 'R12008', 'R11975_v1', 'R04904_v2', 'R03871_v1', 'R07974_v1', 'R02156_v2', 'R01962', 'R11961', 'R12081_v1', 'R02382_v2', 'R05229_v1', 'R07214_v1', 'R07061_v1', 'R02909_v1', 'R11711_v3', 'R02457_v1', 'R07972', 'R12445', 'R11980_v1', 'R08920', 'R09503_vX', 'R10181_v1', 'R06449', 'R00558_v1', 'R00466', 'R08211_v1', 'R05405_v1', 'R02519_v1', 'R05723_v1', 'R01711_v1', 'R04025_v1', 'R10878', 'R00818_v1', 'R02670_v1', 'R00044_v1', 'R00689_v2', 'R01710_v1', 'R02521_v1', 'R12058_v1', 'R02919_v1', 'R01879_v1', 'R10729_v1', 'R12154_v1', 'R07978_v1', 'R09565_v1', 'R00975_v1', 'R02657_v1', 'R00111_v2', 'R02529_v1', 'R01296_v1', 'R11346_v1', 'R02382_v1', 'R07977_v1', 'R07965_v1', 'R11358_v1', 'R10206_v1', 'R08854', 'R12441', 'R08611_v1', 'R10108', 'R12367_v1', 'R10875', 'R11738_v1', 'R00648_v2', 'R10559_v1', 'R02666', 'R02656_v1', 'R02078_v1', 'R07400_v1', 'R06540_v1', 'R07966_v1', 'R02106', 'R04027_v4', 'R10191_v1', 'R07526_v1', 'R07665', 'R10359', 'R07983', 'R01299_v1', 'R10070_v1', 'R07415', 'R10789_v1', 'R08836', 'R07961_v1', 'R10045_v1', 'R10628_v1', 'R07869_v1', 'R02173_v2', 'R01507', 'R08832', 'R10043_v1', 'R11918_v1', 'R03590_v1', 'R12228_v1', 'R05822', 'R02514_v1', 'R08391', 'R02449_v2', 'R00648_v1', 'R05036_v1', 'R04027_v2', 'R11037', 'R07188_v1', 'R11381', 'R07221_v2', 'R11730', 'R07491_v1', 'R08838', 'R04674_v2', 'R12545', 'R11570', 'R02107_v1', 'R02516_v1', 'R07409_v2', 'R00815_v1', 'R07509_v1', 'R08168_v1', 'R06946_v1', 'R11981_v1', 'R01452', 'R05488_v1', 'R06526_v1', 'R12717', 'R00893_v1', 'R07969_v1', 'R04221_v1', 'R11459_v1', 'R03640_v1', 'R01151_v4', 'R00793', 'R04987_v1', 'R11713_v2', 'R06952_v1', 'R07954_v1', 'R00357_v1', 'R02823_v1', 'R07979_v2', 'R04894_v1', 'R06154_v3', 'R12323_v1', 'R02076_v1', 'R03891_v1', 'R11656_v1', 'R00277_v1', 'R06700', 'R10357', 'R01459_v1', 'R11468', 'R02173_v1', 'R06622_v1', 'R09860_v2', 'R09810', 'R00980_v1', 'R01815_v1', 'R12173_v1', 'R00360_v1', 'R08678_v1', 'R10373', 'R11097_v1', 'R05739_v2', 'R06953_v1', 'R02075_v1', 'R07057_v1', 'R11273', 'R10072', 'R07976_v1', 'R11946_v1', 'R09504_v1', 'R11572', 'R07409_v1', 'R11056', 'R10350', 'R01151_v3', 'R10843_v1', 'R00608_v1', 'R09514_v1', 'R08212_v1', 'R03871_v2', 'R04674_v4', 'R10366', 'R12451_v1', 'R06740_v1', 'R05519', 'R08604', 'R11356_v1', 'R05334_v1', 'R02589_v1', 'R10361', 'R01260', 'R01564_v1', 'R08204_v1', 'R00557_v1', 'R12306_v1', 'R12446', 'R12224_v1', 'R07968_v1', 'R12356_v1', 'R05426_v1', 'R03559_v1', 'R07959', 'R10381', 'R07933_v1', 'R10517_v1', 'R11355_v1', 'R09583_v1', 'R11284', 'R00993', 'R07221_v1', 'R06786_v1', 'R08009_v1', 'R01960_v1', 'R02529_v3', 'R10562_v1', 'R03184_v1', 'R11805_v1', 'R00070', 'R01910_v1', 'R00148_v1', 'R02444_v1', 'R03281', 'R10155_v1', 'R02518', 'R07214_v2', 'R12172_v1', 'R10027_v1', 'R06525_v1', 'R05521_v1', 'R02160_v1', 'R07864_v1', 'R00275_v1', 'R05861_v1', 'R00731_v1', 'R01803_v1', 'R11357_v1', 'R00646', 'R07445', 'R03440', 'R02535_v1', 'R12508_v1', 'R11737_v1', 'R02673_v1', 'R10517_v2', 'R00643_v1', 'R11011', 'R11267', 'R03637_v1', 'R06787_v1', 'R03253_v1', 'R05621_v1', 'R02150_v1', 'R10312_v1', 'R00275_v2', 'R00475_v1', 'R07463_v1', 'R03220_v1', 'R12546', 'R08770', 'R03126_v1', 'R08050_v1', 'R02529_v4', 'R11549_v1', 'R04674_v3', 'R09272_v1', 'R10626_v1', 'R03246', 'R02197_v1', 'R00032_v1', 'R05417', 'R03568_v1', 'R12076_v1', 'R12442', 'R00072_v1', 'R03439', 'R11579', 'R09555_v1', 'R06572', 'R09125_v1', 'R08826', 'R12225_v1', 'R07171_v1', 'R00610_v1', 'R04300_v3', 'R00678_v1', 'R12048', 'R07993_v1', 'R08081_v1', 'R04085_v1', 'R07977_v2', 'R04061_v1', 'R10081', 'R06254', 'R05724_v1', 'R11653_v1', 'R11912_v1', 'R10154_v1', 'R12444', 'R12547', 'R08203_v1', 'R03814_v1', 'R10356', 'R09860_v1', 'R11577', 'R02173_v4', 'R04178_v1', 'R12319_v1', 'R02486_v1', 'R11960', 'R11458_v1', 'R11734_v1', 'R11382_v1', 'R11986_v1', 'R04048', 'R12369', 'R10157_v1', 'R02373', 'R01151_v2', 'R12715', 'R02150_v2', 'R10207', 'R12403_v1', 'R02363_v1', 'R11001_v1', 'R11385_v1', 'R07971', 'R08607_v1', 'R08762_v1', 'R01099_v1', 'R11013_v1', 'R11121', 'R11383_v1', 'R07957_v1', 'R07975_v1', 'R02613_v2', 'R12216_v1', 'R03549_v1', 'R02923_v1', 'R00816_v1', 'R02150_v4', 'R09572_v1', 'R06154_v1', 'R05522_v1', 'R11325_v1', 'R04027_v1', 'R00679_v1', 'R04872_v1', 'R07712_v1', 'R00074_v3', 'R07530_v1', 'R11403', 'R07962_v1', 'R11985_v1', 'R00817_v1', 'R08408_v1', 'R01412_v1', 'R10145_v1', 'R06740_v2', 'R03139_v4', 'R05725_v1', 'R03562', 'R05697_v1', 'R09935_v1', 'R07711', 'R08764_v1', 'R11227_v1', 'R09075_v1', 'R01143_v1', 'R11712_v3', 'R12448', 'R02613_v4', 'R06758_v1', 'R10557_v1', 'R00207_v1', 'R11741_v1', 'R07942_v2', 'R10260_v1', 'R07598_v1', 'R11982_v1', 'R09784_v1', 'R07198_v1', 'R01769_v2', 'R06573', 'R11816', 'R07538_v1', 'R05623_v1', 'R05622_v1', 'R00357_v2', 'R09785', 'R06632_v1', 'R09838_v1', 'R07215_v1', 'R09495_v1', 'R12301', 'R12082_v1', 'R01628_v1', 'R05427_v1', 'R08896_v1', 'R07363_v1', 'R05270_v1', 'R12053', 'R00729_v1', 'R10724_v1', 'R07187_v1', 'R12658', 'R00069_v1', 'R01795_v1', 'R00825_v1', 'R11604_v1', 'R03408', 'R03873', 'R02702_v1', 'R11491_v1', 'R10362', 'R12067_v2', 'R05778_v1', 'R00319_v1', 'R07963', 'R04085_v2', 'R06154_v4', 'R03999_v1', 'R01142_v1', 'R05740_v1', 'R12302_v1', 'R06865', 'R08010_v1', 'R00302_v1', 'R05739_v1', 'R00031_v1', 'R02950_v1', 'R12320_v1', 'R08762_v2', 'R09389_v1', 'R12368', 'R12009', 'R06740_v4', 'R11976_v1', 'R07216', 'R07185_v1', 'R10670_v1', 'R12716', 'R00278_v1', 'R10203_v1', 'R07709_v1', 'R00823_v1', 'R02529_v2', 'R07955_v1', 'R04089_v1', 'R07366_v1', 'R06266_v1', 'R08853', 'R12010_v1', 'R02222_v1', 'R08828', 'R05334_v4', 'R08205_v1', 'R00279_v1', 'R06501', 'R02197_v2', 'R06792', 'R05440', 'R10415_v1', 'R00042_v1', 'R03365', 'R01506', 'R07960', 'R09812_v1', 'R00120_v1', 'R11119', 'R01769_v1', 'R02156_v3', 'R10106', 'R03722_v1', 'R00111_v1', 'R05295_v1', 'R05274_v1', 'R08610_v1', 'R11380_v1', 'R05334_v2', 'R10518_v1', 'R12229_v1', 'R10914_v1', 'R00359_v2', 'R00846_v1', 'R09747_v1', 'R10920_v1', 'R04908_v1', 'R10879', 'R07186_v1', 'R06398_v1', 'R02125_v1', 'R11014', 'R06788_v1', 'R04328_v1', 'R00275_v3', 'R02382_v3', 'R12355', 'R08005_v1', 'R02394_v1', 'R05321', 'R08768_v1', 'R11711_v2', 'R10578_v1', 'R07505', 'R11658_v1', 'R07217', 'R02698_v1', 'R00447_v1', 'R02150_v3', 'R01098_v1', 'R12501', 'R01022_v1', 'R02467_v1', 'R08851', 'R00080_v1', 'R05317_v1', 'R08902_v1', 'R01142', 'R09519_v1', 'R07942_v1', 'R05666_v1', 'R11003_v1', 'R02829', 'R07981', 'R02908_v1', 'R03566_v1', 'R01695', 'R09393_v1', 'R01851_v1', 'R03560_v1', 'R10358', 'R04300_v1', 'R01629_v1', 'R07537_v1', 'R11349_v1', 'R00980_v2', 'R12544', 'R06470', 'R11983_v1', 'R00448_v1', 'R12651_v1', 'R11996_v1', 'R10560_v1', 'R11352_v1', 'R06463_v1', 'R02562_v1', 'R06783_v1', 'R12370', 'R06851', 'R05718_v1', 'R03140_v1', 'R07996_v1', 'R09937', 'R12067_v1', 'R03222_v1', 'R11043_v1', 'R11384_v1', 'R02339', 'R08408_v2', 'R05695_v1', 'R02156_v1', 'R11012', 'R03139_v3', 'R05450', 'R08082_v1', 'R07518_v1', 'R10577_v1', 'R12377', 'R01522_v1', 'R02382_v4', 'R11361_v1', 'R01709_v1', 'R05416', 'R12153_v1', 'R05469_v1', 'R03097', 'R03628_v1', 'R02517_v1', 'R09579_v1', 'R12052', 'R08008_v1', 'R05334_v3', 'R07710_v1', 'R01709_v2', 'R05322', 'R00635_v1', 'R10637', 'R00698_v1', 'R00690_v1', 'R00359_v1', 'R05246_v1', 'R05696_v1', 'R00533_v1', 'R04300_v2', 'R07172_v1', 'R08921_v1', 'R04027_v3', 'R02515_v1', 'R03385_v1', 'R04300_v4', 'R10192_v1', 'R00069_v2', 'R00055', 'R08664', 'R10107', 'R03303_v1', 'R00074_v1', 'R03626_v1', 'R07956_v1', 'R11594_v1', 'R03998_v1', 'R02520', 'R04884_v1', 'R05821', 'R06454', 'R09936', 'R02204_v1', 'R05444_v1', 'R02449_v1', 'R10723_v1', 'R07212_v1', 'R12083_v1', 'R06265_v1', 'R03220_v2', 'R03139_v2', 'R09083_v1', 'R11643', 'R01297_v1', 'R05404_v1', 'R07970_v1', 'R00211_v1', 'R01632_v1', 'R03386_v1', 'R01469_v1', 'R02132_v1', 'R08653', 'R03550_v1', 'R00559_v1', 'R09586_v1', 'R07225_v1', 'R07506_v1', 'R10558_v1', 'R03608_v1', 'R01151_v1', 'R07213_v1', 'R11748_v1', 'R11268', 'R03831_v1', 'R04276_v1', 'R10351', 'R10230_v1', 'R05301_v1', 'R08908_v1', 'R04674_v1', 'R05148_v1', 'R05273', 'R01298_v1', 'R09385_v1', 'R11657_v1', 'R03638_v1', 'R02550_v1', 'R10627_v1', 'R01453', 'R12205', 'R12177_v1', 'R11404', 'R12650_v1', 'R01631_v1', 'R07964', 'R05862_v1', 'R10376', 'R07152_v1', 'R00635_v2', 'R01442_v2', 'R07440', 'R09786_v1', 'R00681_v1', 'R05468_v1', 'R10053_v1', 'R11917_v1', 'R11008_v1', 'R07453', 'R08864_v1', 'R01442_v1', 'R03139_v1', 'R04907_v1', 'R11904', 'R10725_v1', 'R00273_v1', 'R09518', 'R12227_v1', 'R11949_v1', 'R07452', 'R11713_v1', 'R02445_v1', 'R00729_v2', 'R06464_v1', 'R00068_v1', 'R01914_v1', 'R09363_v1', 'R11360_v1', 'R09077_v1', 'R07967_v1', 'R01630_v1', 'R07056', 'R04893_v1', 'R07714', 'R06740_v3', 'R12226_v1', 'R10704_v1', 'R07939_v1', 'R00366_v1', 'R11007_v1', 'R07365_v1', 'R01252_v1', 'R02561_v1', 'R11153', 'R10844_v1', 'R00078_v1', 'R11492_v1', 'R10656_v1', 'R07559_v1', 'R10144_v1', 'R02107_v2', 'R07973_v1', 'R07700', 'R12101_v1', 'R01803_v2', 'R11394_v1', 'R05425_v1', 'R11359_v1', 'R11015_v1', 'R11711_v1', 'R10602_v1', 'R11712_v2', 'R09782', 'R09603_v1', 'R00449_v1', 'R12178_v1', 'R02715_v1', 'R00558_v2', 'R00557_v2', 'R00481_v1', 'R10446_v1', 'R11044_v1', 'R09076_v1', 'R00689_v1', 'R09811', 'R11578_v1', 'R12277_v1', 'R06154_v2', 'R00074_v2', 'R08762_v3', 'R02613_v3', 'R02665_v1', 'R10796_v1', 'R02613_v1', 'R00275_v4', 'R02125_v2', 'R12051', 'R00730_v1', 'R00045_v1', 'R07364_v1', 'R00677_v1', 'R11916_v1', 'R03299_v1', 'R06462_v1', 'R12420', 'R07979_v1', 'R09859_v1', 'R04886', 'R04570_v1', 'R02681_v1', 'R06782_v1', 'R10877', 'R05228', 'R00250_v1', 'R01303', 'R07558_v1', 'R00058_v1', 'R06957_v1', 'R02254', 'R11948', 'R07211_v1', 'R11457_v1', 'R02338_v1'}

for rn in directO2:
    d = metabolism.network.loc[metabolism.network['rn'] == rn]
    if 'reverse' in list(d['direction']):
        print(rn)

R03871_v1
R02550_v1
R00793
R05273
R00069_v1
R01303
R05228
R00275_v4
R02657_v1
R00275_v3
R00275_v2
R04328_v1
R02657_v2
R09503_vX
R05229_v1
R03873
R03871_v2
R05036_v1
R00275_v1
R00069_v2
R05280

In [4]:
asset_path = nf.asset_path

METABOLISM_PATH = PurePath(asset_path, "metabolic_networks","metabolism.v8.01May2023.pkl") # path to metabolism object pickle
df1 = pd.read_pickle(METABOLISM_PATH).network

METABOLISM_PATH = PurePath(asset_path, "metabolic_networks","metabolism.v8.02Jun2024_peroxide_fix.pkl") # path to metabolism object pickle
df2 = pd.read_pickle(METABOLISM_PATH).network

In [51]:
df1[df1['rn'] == 'R00839_v2']

             rn direction     cid    s   ub            lb stoich_str  rn_old
4922  R00839_v2   forward  C04534 -1.0  0.1  1.000000e-07        NaN  R00839
4923  R00839_v2   forward  C00001 -1.0  0.1  1.000000e-07        NaN  R00839
4924  R00839_v2   forward  C00031  1.0  0.1  1.000000e-07        NaN  R00839
4925  R00839_v2   forward  C00092  1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   forward  Z00032 -1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v2   forward  Z00030 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   forward  Z00032  1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v2   forward  Z00030  1.0  0.1  1.000000e-07        NaN  R00839
4926  R00839_v2   reverse  C04534  1.0  0.1  1.000000e-07        NaN  R00839
4927  R00839_v2   reverse  C00001  1.0  0.1  1.000000e-07        NaN  R00839
4928  R00839_v2   reverse  C00031 -1.0  0.1  1.000000e-07        NaN  R00839
4929  R00839_v2   reverse  C00092 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   reverse  Z00032 -1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v2   reverse  Z00030 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   reverse  Z00032  1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v2   reverse  Z00030  1.0  0.1  1.000000e-07        NaN  R00839

In [52]:
df2[df2['rn'] == 'R00839_v2']

             rn direction     cid    s   ub            lb stoich_str  rn_old
4922  R00839_v2   forward  C04534 -1.0  0.1  1.000000e-07        NaN  R00839
4923  R00839_v2   forward  C00001 -1.0  0.1  1.000000e-07        NaN  R00839
4924  R00839_v2   forward  C00031  1.0  0.1  1.000000e-07        NaN  R00839
4925  R00839_v2   forward  C00092  1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   forward  Z00069 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   forward  Z00069  1.0  0.1  1.000000e-07        NaN  R00839
4926  R00839_v2   reverse  C04534  1.0  0.1  1.000000e-07        NaN  R00839
4927  R00839_v2   reverse  C00001  1.0  0.1  1.000000e-07        NaN  R00839
4928  R00839_v2   reverse  C00031 -1.0  0.1  1.000000e-07        NaN  R00839
4929  R00839_v2   reverse  C00092 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   reverse  Z00069 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v2   reverse  Z00069  1.0  0.1  1.000000e-07        NaN  R00839

In [5]:
df2[df2['rn'] == 'R00839_v3']

             rn direction     cid    s   ub            lb stoich_str  rn_old
4922  R00839_v3   forward  C04534 -1.0  0.1  1.000000e-07        NaN  R00839
4923  R00839_v3   forward  C00001 -1.0  0.1  1.000000e-07        NaN  R00839
4924  R00839_v3   forward  C00031  1.0  0.1  1.000000e-07        NaN  R00839
4925  R00839_v3   forward  C00092  1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v3   forward  Z00032 -1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v3   forward  Z00030 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v3   forward  Z00032  1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v3   forward  Z00030  1.0  0.1  1.000000e-07        NaN  R00839
4926  R00839_v3   reverse  C04534  1.0  0.1  1.000000e-07        NaN  R00839
4927  R00839_v3   reverse  C00001  1.0  0.1  1.000000e-07        NaN  R00839
4928  R00839_v3   reverse  C00031 -1.0  0.1  1.000000e-07        NaN  R00839
4929  R00839_v3   reverse  C00092 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v3   reverse  Z00032 -1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v3   reverse  Z00030 -1.0  0.1  1.000000e-07        NaN  R00839
0     R00839_v3   reverse  Z00032  1.0  0.1  1.000000e-07        NaN  R00839
1     R00839_v3   reverse  Z00030  1.0  0.1  1.000000e-07        NaN  R00839

In [64]:
df1[df1['rn'] == 'R00946_v1']

             rn direction     cid    s   ub            lb stoich_str  rn_old
5656  R00946_v1   forward  C00440 -1.0  0.1  1.000000e-07        NaN  R00946
5657  R00946_v1   forward  C00155 -1.0  0.1  1.000000e-07        NaN  R00946
5658  R00946_v1   forward  C00101  1.0  0.1  1.000000e-07        NaN  R00946
5659  R00946_v1   forward  C00073  1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   forward  Z00018 -1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   forward  Z00018  1.0  0.1  1.000000e-07        NaN  R00946
5660  R00946_v1   reverse  C00440  1.0  0.1  1.000000e-07        NaN  R00946
5661  R00946_v1   reverse  C00155  1.0  0.1  1.000000e-07        NaN  R00946
5662  R00946_v1   reverse  C00101 -1.0  0.1  1.000000e-07        NaN  R00946
5663  R00946_v1   reverse  C00073 -1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   reverse  Z00018 -1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   reverse  Z00018  1.0  0.1  1.000000e-07        NaN  R00946

In [65]:
df2[df2['rn'] == 'R00946_v1']

             rn direction     cid    s   ub            lb stoich_str  rn_old
5656  R00946_v1   forward  C00440 -1.0  0.1  1.000000e-07        NaN  R00946
5657  R00946_v1   forward  C00155 -1.0  0.1  1.000000e-07        NaN  R00946
5658  R00946_v1   forward  C00101  1.0  0.1  1.000000e-07        NaN  R00946
5659  R00946_v1   forward  C00073  1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   forward  Z00018 -1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   forward  Z00018  1.0  0.1  1.000000e-07        NaN  R00946
5660  R00946_v1   reverse  C00440  1.0  0.1  1.000000e-07        NaN  R00946
5661  R00946_v1   reverse  C00155  1.0  0.1  1.000000e-07        NaN  R00946
5662  R00946_v1   reverse  C00101 -1.0  0.1  1.000000e-07        NaN  R00946
5663  R00946_v1   reverse  C00073 -1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   reverse  Z00018 -1.0  0.1  1.000000e-07        NaN  R00946
0     R00946_v1   reverse  Z00018  1.0  0.1  1.000000e-07        NaN  R00946

# making 'rns_unreached_wo_cofactor' pkl files

In [ ]:
import pickle
full_rns_scope = fm.scope.rns

In [ ]:
print(len(full_rns_scope), len(fm.scope.rns))

my_set = full_rns_scope - fm.scope.rns
print(len(my_set))

In [ ]:
# with open('../rns_unreached_wo_AcetylCoA.pkl', 'wb') as file:
#     pickle.dump(my_set, file)

# what are the 3 compounds that fall off?

In [ ]:
len(fm.scope.cpds), len(set((pd.read_csv(SEED_CPDS_PATH)["ID"]))), len(seed.cpds)

In [ ]:
run_seeds = []
for c, i in fm.scope.cpd_iteration_dict.items():
    if i == 0:
        run_seeds.append(c)
len(run_seeds)

In [ ]:
for c in ['C00034', 'Z00020', 'C00050']:
    print(c, cpd2name[c], ':', c in seed.cpds, c in fm.scope.cpds)

# analysis

In [ ]:
import re
import csv
import ast
import matplotlib.pyplot as plt
import pandas as pd
import random
from bokeh.plotting import figure, output_file, show
from bokeh.models import HoverTool

def todata(dict1, dict2, val_type = 'MEAN'):
    valid_keys = list(dict1.keys() & dict2.keys())
    data1 = [dict1[x] for x in valid_keys]
    data2 = [dict2[x] for x in valid_keys]
    
    if type(data1[0]) == dict:
        data1 = [x[val_type] for x in data1]
        
    if type(data2[0]) == dict:
        data2 = [x[val_type] for x in data2]
    
    return valid_keys, data1, data2

def dict2csv(my_dict, csv_file_path):
    with open(csv_file_path, 'w', newline='') as csv_file:
        csv_writer = csv.writer(csv_file)
        for key, value in my_dict.items():
            csv_writer.writerow([key] + [value])

def csv2dict(csv_file_path):
    result_dict = {}
    with open(csv_file_path, 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        
        for row in csv_reader:
            try:
                result_dict[row[0]] = ast.literal_eval(row[1])  # value is list
            except:
                result_dict[row[0]] = row[1]
                
    return result_dict

def scatter(dict1, dict2, x_axis = 'x-axis', y_axis = 'y-axis'):
    valid_keys, data1, data2 = todata(dict1, dict2)
    plt.scatter(data1, data2, marker='o', color='b', alpha = 0.1, label='Data Points', zorder=2)
    plt.xlabel(x_axis)
    plt.ylabel(y_axis)
    # plt.savefig('scatter.png')
    plt.show()

In [ ]:
module2name = csv2dict('../data/assets/module2name.csv')
module2rns = csv2dict('../data/assets/module2rns.csv')

rn2modules = csv2dict('../data/assets/rn2modules.csv')
rn2def = csv2dict('../data/assets/rn2def_versions.csv')
rn2rules = pd.read_pickle('../data/assets/rn2rules.20230224.pkl')
rn2eqn_SI = csv2dict('../data/assets/rn2eqn_SI.csv')
cpd2name = csv2dict('../data/assets/cpd2nameShort.csv')

# vanilla

In [ ]:
vanilla_iter2cpds = {}
for c, i in fm.scope.cpd_iteration_dict.items():
    if i not in vanilla_iter2cpds.keys():
        vanilla_iter2cpds[i] = [c]
    else:
        vanilla_iter2cpds[i].append(c)
        
vanilla_iter2cpdsNum = {}
for i in vanilla_iter2cpds.keys():
    vanilla_iter2cpdsNum[i] = len(vanilla_iter2cpds[i])
    
plt.figure(figsize=(30, 5))
plt.plot(vanilla_iter2cpdsNum.values(), color='k')
plt.xlim([0, 85])
plt.ylim([0, 260])
plt.xticks(fontsize='18')
plt.yticks(fontsize='18')
# plt.savefig('vanilla_iter_vs_cpds_10AA.svg', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
# annotate cpds

cpd2iter = {}
for cpd in ['C0007', 'C00018', 'C00302', 'C00334', 'C11440', 'C00002', 'C00003', 'C00010', 'C00024', 'C00129', 'C00068', 'C00019', 'C00101', 'C00016', 'C00061', 'C00363', 'C00194', 'C00062', 'C00007', 'C00448', 'C11901', 'C00341', 'C00353', 'C00923', 'C00463', 'C00229', 'C05819', 'C03313', 'C00027', 'C00032', 'C00059', 'C00094', 'C05773', 'C00251', 'C00082', 'C00079', 'C00078', 'C02059', 'C00828', 'C01063', 'C00120']:
    for i, cs in vanilla_iter2cpds.items():
        for c in cs:
            if c == cpd:
                cpd2iter[c] = i

In [ ]:
plt.figure(figsize=(30, 5))
plt.plot(vanilla_iter2cpdsNum.values(), color='k')

# annotate cpds

for c in cpd2iter:
    y = random.randint(0, 250)
    plt.text(cpd2iter[c], y, cpd2name[c], ha='center', va='bottom', color='red')
    plt.scatter(cpd2iter[c], y-5, color='red')

# plt.savefig('3B_cpds_vanilla.svg', dpi=300, bbox_inches='tight')
plt.show()

# fold-gated

In [ ]:
result = pd.read_pickle('../runs/2024-04-25_11-00-45_no_look_ahead_rules_ignore_versions_3141_cumiter_fix.pkl.gz')

In [ ]:
folditer2cpd = {}
for c, order in result.cpds_folditer.items():
    if order not in folditer2cpd.keys():
        folditer2cpd[order] = [c]
    else:
        folditer2cpd[order].append(c)
print(len(folditer2cpd))

folditer2cpdNum = {}
for fold in folditer2cpd.keys():
    folditer2cpdNum[fold] = len(folditer2cpd[fold])

folditer2cpdNumFull = {}
for i in range(0, max(folditer2cpd.keys())):
    if i not in folditer2cpdNum.keys():
        folditer2cpdNumFull[i] = 0
    else:
        folditer2cpdNumFull[i] = folditer2cpdNum[i]
        
plt.figure(figsize=(30, 5))
plt.plot(folditer2cpdNumFull.values(), color='k')

plt.xlim([0, 360])
# plt.savefig('3B_cpds.png', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
# from pre-expansion
cpds = ['Z00035', 'C00002', 'C00004', 'C00019', 'C00010', 'C00016', 'Z00047', 'Z00009']
# from vanilla (+ FMN, AcetylCoA, isopentenyl diphosphate, oxygen)
cpds = ['C00007','C00024','C00061','C00129','Z00014', 'Z00035', 'C00002', 'C00004', 'C00019', 'C00010', 'C00016', 'Z00047', 'Z00009']

dict1 = result.cpds_folditer
dict2 = fm.scope.cpd_iteration_dict

# if you don't care about zorder of red vs. blue
# valid_keys, data1, data2 = todata(dict1, dict2)
# colors = ['red' if c in cpds else 'blue' for c in valid_keys]
# plt.scatter(data1, data2, marker='o', color=colors, alpha = 0.5, label='Data Points', zorder=2)

# if you red in front of blue
booleans = [c in cpds for c in valid_keys]
data1_bool = [value for value, flag in zip(data1, booleans) if flag]
data2_bool = [value for value, flag in zip(data2, booleans) if flag]
plt.scatter(data1, data2, marker='o', color='blue', alpha = 0.1, label='Data Points', zorder=2)
plt.scatter(data1_bool, data2_bool, marker='o', color='red', alpha = 0.5, label='Data Points', zorder=3)

# annotate cpds
for c in cpds:
    plt.text(dict1[c], dict2[c], cpd2name[c], ha='center', va='bottom', color='red')

plt.ylabel('vanilla')
plt.xlabel('fold_gated')
# plt.savefig('scatter_vanilla_vs_fold_gated_key_cpds.svg')
plt.show()

In [ ]:
# bokeh

output_file("vanilla_vs_fold_gated_order.html")
p = figure(plot_width=800, plot_height=800, title="vanilla_vs_fold_gated_order")

# Add annotations
# source = {'x': list(group12iter.values()), 'y': y_values, 'label': ['X' + str(key) for key in group12iter.keys()]}
dict1 = {key:value for key, value in result.cpds_folditer.items() if key not in cpds}
dict2 = {key:value for key, value in fm.scope.cpd_iteration_dict.items() if key not in cpds}
valid_keys, data1, data2 = todata(dict1, dict2)

dict1_red = {key:value for key, value in result.cpds_folditer.items() if key in cpds}
dict2_red = {key:value for key, value in fm.scope.cpd_iteration_dict.items() if key in cpds}
valid_keys_red, data1_red, data2_red = todata(dict1_red, dict2_red)

source = {'x': data1, 'y': data2, 'label': [cpd2name.get(key, 'no name') for key in valid_keys]}
p.scatter('x', 'y', source=source, size=10, color='blue', alpha=0.3)

source = {'x': data1_red, 'y': data2_red, 'label': [cpd2name.get(key, 'no name') for key in valid_keys_red]}
p.scatter('x', 'y', source=source, size=10, color='red', alpha=0.3)

# Add hover tool
hover = HoverTool()
hover.tooltips = [("folditer", "@x"), ("cpd", "@label")]
p.add_tools(hover)

# Customize plot
p.xaxis.axis_label = 'fold_gated'
p.yaxis.axis_label = 'vanilla'
p.xaxis.ticker = [50, 100, 150, 200, 250, 300, 350]  # Convert range to list
p.xgrid.grid_line_color = None

# Show the plot
show(p)

# carbon fixation pathways: validating result from vanilla

In [ ]:
cm = ['M00165', 'M00173', 'M00374', 'M00375', 'M00376', 'M00377']

In [ ]:
cm2rn = {}

for m in cm:
    print(m, module2name[m])
    print(module2rn[m])
    cm2rn[m] = set(module2rn[m])
    
    # check if any module is satisfied in vanilla
    print(all(item in [item[:6] for item in fm.scope.rns] for item in module2rn[m]))
    
    print('')

In [ ]:
iter2rn = {}

for rn, i in fm.scope.rn_iteration_dict.items():
    if i not in iter2rn.keys():
        iter2rn[i] = [rn]
    else:
        iter2rn[i].append(rn)

In [ ]:
cm = ['M00165', 'M00173', 'M00374', 'M00375', 'M00376', 'M00377']
rn_list = []

for i, rns in iter2rn.items():
    # keep updating rn_list
    rn_list.extend(rns)
    
    # for each cm module, check if all rns in module are in rn_list
    for m in cm:
        if all(item in [item[:6] for item in rn_list] for item in module2rn[m]):
            print(f'{m}: {module2name[m]} is feasible at {i}')
            cm.remove(m)

## with fold-gating

In [ ]:
withP = pd.read_pickle('../2024-04-19_19-53-04_with_protein.pkl.gz')

In [ ]:
withP.iteration_cum

In [ ]:
iter2rn = {}

for rn, i in withP.rns_cumiter.items():
    if i not in iter2rn.keys():
        iter2rn[i] = [rn]
    else:
        iter2rn[i].append(rn)

In [ ]:
cm = ['M00165', 'M00173', 'M00374', 'M00375', 'M00376', 'M00377']
rn_list = []

for i, rns in iter2rn.items():
    # keep updating rn_list
    rn_list.extend(rns)
    
    # for each cm module, check if all rns in module are in rn_list
    for m in cm:
        if all(item in [item[:6] for item in rn_list] for item in module2rn[m]):
            print(f'{m}: {module2name[m]} is feasible at {i}')
            cm.remove(m)

# checking cofactor dependence: two directions

In [ ]:
import csv
import ast

def csv2dict(csv_file_path):
    result_dict = {}
    with open(csv_file_path, 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        
        for row in csv_reader:
            try:
                result_dict[row[0]] = ast.literal_eval(row[1])  # value is list
            except:
                result_dict[row[0]] = row[1]
                
    return result_dict

rn2cpds_SI = csv2dict('../data/assets/rn2cpds_SI.csv')
rn2def_SI = csv2dict('../data/assets/rn2def_complete.csv')
cpd2name = csv2dict('../data/assets/cpd2nameShort.csv')

In [ ]:
cpd2name['C00003'], cpd2name['C01352']

In [ ]:
# FAD+/FADH2

for rn, cpds in rn2cpds_SI.items():
    if 'C00016' in cpds:
        if 'C01352' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))
print('-----')
for rn, cpds in rn2cpds_SI.items():
    if 'C01352' in cpds:
        if 'C00016' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))

In [ ]:
# NAD+/NADH

for rn, cpds in rn2cpds_SI.items():
    if 'C00003' in cpds:
        if 'C00004' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))
print('-----')
for rn, cpds in rn2cpds_SI.items():
    if 'C00004' in cpds:
        if 'C00003' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))

In [ ]:
# NADP+/NADPH

for rn, cpds in rn2cpds_SI.items():
    if 'C00005' in cpds:
        if 'C00006' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))
print('-----')
for rn, cpds in rn2cpds_SI.items():
    if 'C00006' in cpds:
        if 'C00005' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))

In [ ]:
# ATP/ADP

for rn, cpds in rn2cpds_SI.items():
    if 'C00002' in cpds:
        if 'C00008' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))
print('-----')
for rn, cpds in rn2cpds_SI.items():
    if 'C00008' in cpds:
        if 'C00002' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))

In [ ]:
# SAM/SAH

for rn, cpds in rn2cpds_SI.items():
    if 'C00019' in cpds:
        if 'C00021' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))
print('-----')
for rn, cpds in rn2cpds_SI.items():
    if 'C00021' in cpds:
        if 'C00019' not in cpds:
            print(rn, cpds, rn2def_SI.get(rn[:6], 0))

# compare before 'protein' fix vs. after fix

In [ ]:
vanilla_70seed = csv2dict('../data/assets/vanilla_cpd2iter_70seed.csv')
vanilla_before = csv2dict('../data/assets/vanilla_cpd2iter_before.csv')
vanilla_after = csv2dict('../data/assets/vanilla_cpd2iter_after.csv')

In [ ]:
vanilla_iter2cpds_70 = {}
for c, i in vanilla_70seed.items():
    if i not in vanilla_iter2cpds_70.keys():
        vanilla_iter2cpds_70[i] = [c]
    else:
        vanilla_iter2cpds_70[i].append(c)
        
vanilla_iter2cpds_70Num = {}
for i in vanilla_iter2cpds_70.keys():
    vanilla_iter2cpds_70Num[i] = len(vanilla_iter2cpds_70[i])
    
plt.figure(figsize=(10, 5))
plt.plot(vanilla_iter2cpds_70Num.values(), color='green')
# plt.savefig('3B_cpds_vanilla.svg', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
# from pre-expansion
cpds = ['Z00035', 'C00002', 'C00004', 'C00019', 'C00010', 'C00016', 'Z00047', 'Z00009']

# from vanilla (+ FMN, AcetylCoA, isopentenyl diphosphate, oxygen)
cpds = ['C00007','C00024','C00061','C00129','Z00014', 'Z00035', 'C00002', 'C00004', 'C00019', 'C00010', 'C00016', 'Z00047', 'Z00009']

In [ ]:
# cummulative growth 70 seed

cpds = ['C00007','C00024','C00061','C00129','Z00014', 'Z00035', 'C00002', 'C00004', 'C00019', 'C00010', 'C00016', 'Z00047']
vanilla_iter2cpds_70Num_cumm = {}
cumm = 0
for i, num in vanilla_iter2cpds_70Num.items():
    vanilla_iter2cpds_70Num_cumm[i] = num + cumm
    cumm += num
vanilla_iter2cpds_70Num_cumm

plt.figure(figsize=(6, 5))
plt.plot(vanilla_iter2cpds_70Num_cumm.values(), color='k')

# annotate cpds
for c in cpds:
    x = vanilla_70seed[c]
    y = vanilla_iter2cpds_70Num_cumm[x]
    plt.text(x+7, y-100, cpd2name[c], ha='center', va='bottom', color='red')
    plt.scatter(x, y, marker='o', color='red', alpha = 0.5, label='Data Points', zorder=2)
    
plt.xticks(fontsize='14')
plt.yticks(fontsize='14')
plt.xlabel('Expansion iteration', fontsize='14')
plt.ylabel('Network Size', fontsize='14')

# plt.savefig('vanilla_iter_vs_cumm_cpds_annotated.svg', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
# cummulative growth 80 seed

cpds = ['C00007','C00024','C00061','C00129','Z00014', 'Z00035', 'C00002', 'C00004', 'C00019', 'C00010', 'C00016', 'Z00047']
vanilla_iter2cpds_before_cumm = {}
cumm = 0
for i, num in vanilla_iter2cpds_beforeNum.items():
    vanilla_iter2cpds_before_cumm[i] = num + cumm
    cumm += num
vanilla_iter2cpds_before_cumm

plt.figure(figsize=(6, 5))
plt.plot(vanilla_iter2cpds_before_cumm.values(), color='k')

# annotate cpds
for c in cpds:
    x = vanilla_before[c]
    y = vanilla_iter2cpds_before_cumm[x]
    plt.text(x+7, y-100, cpd2name[c], ha='center', va='bottom', color='red')
    plt.scatter(x, y, marker='o', color='red', alpha = 0.5, label='Data Points', zorder=2)
    
plt.xticks(fontsize='14')
plt.yticks(fontsize='14')
plt.xlabel('Expansion iteration', fontsize='14')
plt.ylabel('Network Size', fontsize='14')

# plt.savefig('vanilla_iter_vs_cumm_cpds_80seed_annotated.svg', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
vanilla_iter2cpds_after = {}
for c, i in vanilla_after.items():
    if i not in vanilla_iter2cpds_after.keys():
        vanilla_iter2cpds_after[i] = [c]
    else:
        vanilla_iter2cpds_after[i].append(c)
        
vanilla_iter2cpds_afterNum = {}
for i in vanilla_iter2cpds_after.keys():
    vanilla_iter2cpds_afterNum[i] = len(vanilla_iter2cpds_after[i])
    
plt.figure(figsize=(30, 5))
plt.plot(vanilla_iter2cpds_afterNum.values(), color='k')
# plt.savefig('3B_cpds_vanilla.svg', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
vanilla_iter2cpds_before = {}
for c, i in vanilla_before.items():
    if i not in vanilla_iter2cpds_before.keys():
        vanilla_iter2cpds_before[i] = [c]
    else:
        vanilla_iter2cpds_before[i].append(c)
        
vanilla_iter2cpds_beforeNum = {}
for i in vanilla_iter2cpds_before.keys():
    vanilla_iter2cpds_beforeNum[i] = len(vanilla_iter2cpds_before[i])

plt.figure(figsize=(30, 5))
plt.plot(vanilla_iter2cpds_beforeNum.values(), color='k')
# plt.savefig('3B_cpds_vanilla.svg', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
scatter(vanilla_after, vanilla_before, 'after', 'before')

In [ ]:
dict1 = vanilla_after
dict2 = vanilla_before

valid_keys, data1, data2 = todata(dict1, dict2)

# if you don't care about zorder of blue vs. red
# colors = ['red' if c in cpds else 'blue' for c in valid_keys]
# plt.scatter(data1, data2, marker='o', color=colors, alpha = 0.1, label='Data Points', zorder=2)

# if you want red to be in front
plt.scatter(data1, data2, marker='o', color='blue', alpha = 0.1, label='Data Points', zorder=2)
booleans = [c in cpds for c in valid_keys]
data1_bool = [value for value, flag in zip(data1, booleans) if flag]
data2_bool = [value for value, flag in zip(data2, booleans) if flag]
plt.scatter(data1_bool, data2_bool, marker='o', color='red', alpha = 0.5, label='Data Points', zorder=2)

# annotate cpds
for c in cpds:
    plt.text(vanilla_after[c], vanilla_before[c], cpd2name[c], ha='center', va='bottom', color='red')

plt.xlabel('after fix')
plt.ylabel('before fix')
# plt.savefig('scatter_vanilla_before_vs_after.svg')
plt.show()

In [ ]:
aa = ['C00017', 'C00037', 'C00077', 'C00041', 'C00097', 'C00049', 'C00025', 'C00079', 'C00135', 'C00407', 'C00047', 'C00123', 'C00073', 'C00152', 'C00148', 'C00064', 'C00062', 'C00065', 'C00188', 'C00183', 'C00078', 'C00082']

dict1 = vanilla_after
dict2 = vanilla_before

valid_keys, data1, data2 = todata(dict1, dict2)
# colors = ['red' if c in cpds else 'blue' for c in valid_keys]
# plt.scatter(data1, data2, marker='o', color=colors, alpha = 0.1, label='Data Points', zorder=2)

plt.scatter(data1, data2, marker='o', color='blue', alpha = 0.1, label='Data Points', zorder=2)
booleans = [c in aa for c in valid_keys]
data1_bool = [value for value, flag in zip(data1, booleans) if flag]
data2_bool = [value for value, flag in zip(data2, booleans) if flag]
plt.scatter(data1_bool, data2_bool, marker='o', color='red', alpha = 0.5, label='Data Points', zorder=2)

# annotate cpds
for c in aa:
    plt.text(vanilla_after[c], vanilla_before[c], cpd2name[c], ha='center', va='bottom', color='red')

plt.xlabel('after fix')
plt.ylabel('before fix')
# plt.savefig('scatter_vanilla_before_vs_after_AA.svg')
plt.show()

In [ ]:
# bokeh

output_file("annotated_plot.html")
p = figure(plot_width=800, plot_height=800, title="cpd order (after) vs. cpd order (before)")

# Add annotations
# source = {'x': list(group12iter.values()), 'y': y_values, 'label': ['X' + str(key) for key in group12iter.keys()]}
key, data1, data2 = todata(vanilla_after, vanilla_before)
source = {'x': data1, 'y': data2, 'label': [cpd2name.get(key, 'no name') for key in key]}
p.scatter('x', 'y', source=source, size=10, color='blue')

# Add hover tool
hover = HoverTool()
hover.tooltips = [("folditer", "@x"), ("cpd", "@label")]
p.add_tools(hover)

# Customize plot
p.xaxis.axis_label = 'cpd order (after)'
p.yaxis.axis_label = 'cpd order (before)'
p.xaxis.ticker = [50, 100, 150, 200, 250, 300, 350]  # Convert range to list
p.xgrid.grid_line_color = None

# Show the plot
show(p)

# ~50% of seed reactions are 'lost'!

In [ ]:
len(fm.seed.cpds)

In [ ]:
len(fm.seed.rns - fm.scope.rns)  # number of rns in seed that the algo never reaches

In [ ]:
len(fm.seed.rns), len(fm.scope.rns), len(fm.seed.rns & fm.scope.rns)

# get seed sets for pre-expansion

In [ ]:
preexp_cpds = ['Z00035', 'C00002', 'C00004', 'C00019', 'C00010', 'C00016', 'Z00047', 'Z00009']

cpd2seeds = {}
cpd2seeds['NONE'] = fm.seed.cpds

for cpd in preexp_cpds:
    seeds = []
    cpditer = fm.scope.cpd_iteration_dict[cpd]
    for c, i in fm.scope.cpd_iteration_dict.items():
        if i <= cpditer:
            seeds.append(c)
    cpd2seeds[cpd] = seeds

cpd2seeds['ALL'] = fm.scope.cpds

In [ ]:
for c, seeds in cpd2seeds.items():
    print(c, len(seeds))

In [ ]:
# for cpd, seeds in cpd2seeds.items():
#     with open(f'pre-expansion_seed_cpds/pre-expansion_seed_cpds_{cpd}.pkl', 'wb') as file:
#         pickle.dump(seeds, file)

In [ ]:
a = pd.read_pickle('pre-expansion_seed_cpds/pre-expansion_seed_cpds_NONE.pkl')
print(a)

# investigating photosyn_R09503_vX

In [ ]:
rn2eqn_SI['R09503_vX']

In [ ]:
rn2eqn_SI['R09503_v1']

In [ ]:
# according to Liam: new reactions were added to account for the possibility that ancient reactions 
# could be catalyzed with prebiotic, geochemical context; so these reactions are NOT meant to be the same; 
# it's ok that some of them are not fold-gated

# script for shuffle1

In [ ]:
# shuffle2 was done with multiprocessing from PyCharm

In [ ]:
import warnings
warnings.filterwarnings("ignore")
import networkExpansionPy.folds as nf
import pandas as pd
from pathlib import PurePath
import random

def shuffle_dict_pairs(d):
    # Extract keys and values
    keys = list(d.keys())
    values = list(d.values())

    # Shuffle the keys
    random.shuffle(keys)

    # Create a new dictionary with shuffled key-value pairs
    shuffled_dict = dict(zip(keys, values))

    return shuffled_dict


if __name__ == '__main__':
    preNONE = pd.read_pickle(
        '../fold_pre-expansion-results.26Sep2023/2023-09-26_19-25-59_rules_to_rn_randomSeed_42_preExpansion_NONE.pkl.gz')
    preATP = pd.read_pickle(
        '../fold_pre-expansion-results.26Sep2023/2023-09-26_20-37-47_rules_to_rn_randomSeed_42_preExpansion_C00002_iter20.pkl.gz')
    print(len(set(preATP.cpds_subiter[0])))

    asset_path = nf.asset_path

    # for vanilla
    METABOLISM_PATH = PurePath(asset_path, "metabolic_networks",
                               "metabolism.v8.02Jun2024_peroxide_fix.pkl")  # path to metabolism object pickle
    RN2RULES_PATH = PurePath(asset_path, "rn2fold", "rn2rules.20230224.pkl")  # path to rn2rules object pickle
    SEED_CPDS_PATH = PurePath(asset_path, "compounds", "seeds.Goldford2022.csv")  # path to seed compounds csv

    # for FOLD-GATED
    ALGORITHM = "no_look_ahead_rules"
    WRITE = True  # write result to disk
    WRITE_TMP = False  # write after each iteration
    CUSTOM_WRITE_PATH = None  # if writing result, custom path to write to
    ORDERED_OUTCOME = False  # ignore random seed and always choose folds based on sort order
    IGNORE_REACTION_VERSIONS = True  # when maximizing for reactions, don't count versioned reactions

    ## Metabolism
    metabolism = pd.read_pickle(METABOLISM_PATH)

    ## FoldRules
    rn2rules = pd.read_pickle(RN2RULES_PATH)
    RANDOMSEED = 33671
    random.seed(RANDOMSEED)
    # set file name
    STR_TO_APPEND_TO_FNAME = "shuffle1_%s" % RANDOMSEED

    # Inititalize fold metabolism with shuffling
    rn2rules_shuffle = shuffle_dict_pairs(rn2rules)  # Shuffle the dictionary pairs
    foldrules = nf.FoldRules.from_rn2rules(rn2rules_shuffle)
    fm = nf.FoldMetabolism(metabolism, foldrules, seed)

    ## Modify seeds with AA and GATP_rns
    aa_cids = set(["C00037",
                   "C00041",
                   "C00065",
                   "C00188",
                   "C00183",
                   "C00407",
                   "C00123",
                   "C00148",
                   "C00049",
                   "C00025"])

    GATP_rns = {'R00200_gATP_v1',
                'R00200_gATP_v2',
                'R00430_gGTP_v1',
                'R00430_gGTP_v2',
                'R01523_gATP_v1',
                'R04144_gATP_v1',
                'R04208_gATP',
                'R04463_gATP',
                'R04591_gATP_v1',
                'R06836_gATP',
                'R06974_gATP',
                'R06975_gATP_v1'}

    # Seed (modify with pre_expansion seed)
    seed = nf.Params(
        rns = set(metabolism.network["rn"]) - set(rn2rules) | GATP_rns,
        cpds = set(preATP.cpds_subiter[0]) | aa_cids,
        folds = set(['spontaneous'])
    )

    ## Seed (no pre-expansion)
    # seed = nf.Params(
    #     rns=set(metabolism.network["rn"]) - set(rn2rules) | GATP_rns,  # start with non-fold-gated reactions
    #     cpds=set((pd.read_csv(SEED_CPDS_PATH)["ID"])) | aa_cids,
    #     folds=set(['spontaneous'])
    # )

## Inititalize fold metabolism
fm = nf.FoldMetabolism(metabolism, foldrules, seed)

# run FOLD-GATED expansion
result = fm.rule_order(algorithm=ALGORITHM, write=WRITE, write_tmp=WRITE_TMP, path=CUSTOM_WRITE_PATH, str_to_append_to_fname=STR_TO_APPEND_TO_FNAME, ordered_outcome=ORDERED_OUTCOME, ignore_reaction_versions=IGNORE_REACTION_VERSIONS)